### ISSUE TITLE
All contacts are not notified

### ISSUE THREAD

**Issue by algorys** [Alignak-monitoring-contrib/alignak-notifications#6]
I've install `alignak-notifications` on my alignak server and notifications works but I received them only for `admin` user email. The others received nothing :sob: 

Config:

Ubuntu 16.04

```bash
alignak==0.2
alignak-backend==0.8.17
alignak-backend-client==0.9.0
alignak-backend-import==0.9.0
alignak-module-backend==0.5.0
alignak-module-logs==0.5.1
alignak-notifications==0.3.1
alignak-webui==0.8.3.4
```
Objects configurations:

```cfg
# Sample for all my contacts
define contact{
use                 generic-contact
contact_name        <name>
alias               Administrator
email               name@mail.com
...
}
```

```cfg
# Template for all my contacts
define contact{
name                            generic-contact
host_notifications_enabled      1
notificationways                email-html
...
}
```

```cfg
# Template for all my hosts
define host{
name                    generic-host

# Checking part
check_command           _internal_host_up
max_check_attempts      2
check_interval          5

# Check every time
active_checks_enabled   1
check_period            24x7

# Notification part
# One notification each day (1440 = 60min* 24h)
# every time, and for all 'errors'
# notify the admins contactgroups by default
contact_groups          admins
notification_interval   720
notification_period     24x7
notification_options    d,u,r,f
notifications_enabled   1
...
}
```

Does I have to precise email somewhere else ? 

Otherwise all the rest of the configuration seems to work.

**Comment by fpeyre** [comment]
I don't see a contact groups, but only a contact object in your configuration. It is normal ?

**Comment by algorys** [comment]
@fpeyre I've not put my contact group config inside issue, so yes it's normal :yum: 

My "admins" contact group is one by default:

```cfg
define contactgroup{
contactgroup_name   admins
alias               admins
members             admin
}
```

**Comment by fpeyre** [comment]
Ok, so in your contact groups, you have only the user admin as members

**Comment by mohierf** [comment]
IMHO this problem is probably not related to the `alignak-notifications` but rather the the alignak core itself ... this needs to be confirmed.

@algorys : you may set the environment variable `TEST_LOG_ACTIONS` before running the Alginak daemons. This will activate logs in the daemons to track what are the launched scripts. In the reactionner log, you should have the commands executed to send the notifications and, of course, their execution result

**Comment by mohierf** [comment]
Closing this
